# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 08:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комметарий')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 1, 17, 11, 42, 27, 400995))),
            ],
            options={
                'verbose_name': 'Комметарий',
                'verbose_name_plural': 'Комметарии',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок статьи')),
                ('text', models.CharField(max_length=255, verbose_name='Текст поста')),
                ('likes', models.IntegerField(default=0, verbose_name='Понравилось')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 1, 17, 11, 42, 27, 400995))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_massage', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Список постов',
                'ordering': ['date', 'likes', 'title'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.PostMessage'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_massage', to=settings.AUTH_USER_MODEL),
        ),
    ]
